on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: $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
          command: manifest
          release-type: node
          package-name: ArduinoHC05App